name: b2ctechnician
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.1.0
  page_transition: ^2.0.9
  shimmer: ^2.0.0
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.0+1
  animate_do: ^3.0.2
  pinput: ^2.2.31
  simple_circular_progress_bar: ^1.0.2
  image_picker: ^0.8.7+5
  get: ^4.6.5
  intl: ^0.18.1
  gradient_widgets: ^0.6.0
  google_maps_flutter: ^2.2.6
  flutter_rating_bar: ^4.0.1
  toggle_switch: ^2.1.0
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.1.0
  app_settings: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/lognano.png
    - assets/images/logosmart.png
    - assets/images/newPass.png
    - assets/images/otp.png
    - assets/images/forgot.png
    - assets/images/man.jpg
    - assets/images/error.png
    - assets/images/file.png
    - assets/images/notes.png
    - assets/images/suitcase.png
    - assets/images/loginBackground.png
    - assets/images/card.png
    - assets/images/photograph.png
    - assets/images/gallery.png
    - assets/images/folder.png
    - assets/images/inbox.png
    - assets/images/verify.png
    - assets/images/block.png
    - assets/images/cross.png
    - assets/images/sand.png
    - assets/images/tick.png
    - assets/images/usd.png
    - assets/images/b2clogo.png
    -
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
